/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y588YwQ4sGG
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function contact() {
  return (
    <div className="container grid max-w-3xl px-4 gap-10 py-12 md:py-24">
      <div className="space-y-4">
        <div className="space-y-2">
          <h1
            className="text-4xl font-extrabold tracking-tighter sm:text-5xl md:text-6xl">Contact us</h1>
          <p className="text-gray-500 dark:text-gray-400">
            We're here to help. Fill out the form below and we'll get back to you as soon as possible.
          </p>
        </div>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="first-name">First name</Label>
              <Input id="first-name" placeholder="Enter your first name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="last-name">Last name</Label>
              <Input id="last-name" placeholder="Enter your last name" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <Button>Send message</Button>
        </div>
      </div>
    </div>
  );
}

export default contact;
