/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jX5rHBCblFQ
 */
import { Link } from 'react-router-dom';


import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardContent, Card } from "@/components/ui/card"

export function dashboard() {


  function handleLogout() {
    // Logic to clear user session
    // For example, if using localStorage:
    localStorage.removeItem('userToken');
  
    // Redirect to login page
    window.location.href = '/login';
  }


  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center h-14 px-4 border-b lg:h-20 lg:px-6">
        <Button
          className="rounded-full border w-8 h-8 dark:border-gray-800"
          size="icon"
          variant="ghost">
          <Package2Icon className="h-6 w-6" />
          <span className="sr-only">Toggle sidebar</span>
        </Button>
        <nav aria-label="Breadcrumb" className="hidden ml-4 space-x-2 lg:flex">
          <Button className="h-8 w-8 rounded-full" size="icon" variant="ghost">
            <HomeIcon className="w-4 h-4" />
            <span className="sr-only">Home</span>
          </Button>
          <Button className="h-8 rounded-lg" variant="ghost">
            My Cards
          </Button>
        </nav>
        <div className="flex items-center ml-auto gap-4 lg:gap-6">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                className="rounded-full border w-8 h-8 dark:border-gray-800"
                id="user-menu"
                size="icon"
                variant="ghost">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32" />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={handleLogout}>Logout</DropdownMenuItem>        
              </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 overflow-y-auto p-4 md:p-6">
        <div className="mx-auto max-w-6xl space-y-8">
          <div className="flex items-center gap-4">
            <h1 className="text-2xl font-bold tracking-tighter">My Business Cards</h1>
            <Button className="ml-auto" size="sm">
  <Link to="/create" style={{ textDecoration: 'none', color: 'inherit' }}>
    Create
  </Link>
</Button>
          </div>
          <div className="grid gap-4 md:gap-8">
            <Card>
              <CardContent className="flex items-center gap-4 p-4 md:p-6">
                <img
                  alt="Avatar"
                  className="rounded-full border object-cover"
                  height="64"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "64/64",
                    objectFit: "cover",
                  }}
                  width="64" />
                <div className="grid gap-1">
                  <h2 className="font-semibold text-lg">Acme Inc</h2>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Trusted by the best teams in the world. We help teams of all sizes.
                  </p>
                </div>
                <Button className="ml-auto" size="icon">
                  Edit
                </Button>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex items-center gap-4 p-4 md:p-6">
                <img
                  alt="Avatar"
                  className="rounded-full border object-cover"
                  height="64"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "64/64",
                    objectFit: "cover",
                  }}
                  width="64" />
                <div className="grid gap-1">
                  <h2 className="font-semibold text-lg">Bolt</h2>
                  <p className="text-sm text-gray-500 dark:text-gray-400">The fastest way to get around.</p>
                </div>
                <Button className="ml-auto" size="icon">
                  Edit
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}

export default dashboard;


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  );
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}
