/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kDM0I8n8i1F
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function editcard() {
  return (

    <div className="mx-auto max-w-sm space-y-6">
    <Card>
      <CardHeader>
        <CardTitle>Edit contact</CardTitle>
        <CardDescription>Make changes to the contact's information.</CardDescription>
      </CardHeader>
      <CardContent>
        <form>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input defaultValue="Alice Chu" id="name" placeholder="Enter the name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="title">Title</Label>
              <Input defaultValue="CTO" id="title" placeholder="Enter the title" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="company">Company</Label>
              <Input
                defaultValue="Acme Corporation"
                id="company"
                placeholder="Enter the company" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Phone</Label>
              <Input defaultValue="alice@example.com" id="phone" placeholder="Enter the phone" />
            </div>
          </div>
        </form>
      </CardContent>
      <CardFooter>
        <Button>Save</Button>
      </CardFooter>
    </Card>
    </div>
  );
}

export default editcard;
