/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iJua6moD80L
 */
import React, { useState } from 'react';
import axios from 'axios';
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Form } from "react-router-dom"

export function registerform() {

  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
  });

  const handleChange = (e) => {
    const { id, value } = e.target;
    setFormData(prevState => ({
      ...prevState,
      [id]: value,
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://localhost/api/register', formData);
      console.log(response.data);
      window.location.href = '/login';

    } catch (error) {
      console.error('Registration failed:', error.response.data);
    }
  };

  return (
   
    <div className="mx-auto max-w-sm space-y-6">
       <form onSubmit={handleSubmit}>
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Register</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your information to create an account</p>
      </div>
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input id="name" placeholder="Enter your name" required value={formData.name} onChange={handleChange} />      
      </div>
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input id="email" placeholder="Enter your email" required value={formData.email} onChange={handleChange} />
      </div>
      <div className="space-y-2">
        <Label htmlFor="password">Password</Label>
        <Input id="password" placeholder="Enter your password"  type="password" required value={formData.password} onChange={handleChange} />
      </div>
      <Button className="w-full mt-5" type="submit">
        Register
      </Button>
      </form>
    </div>
  );
}

export default registerform;
